apiVersion: v1
kind: Pod
metadata:
  name: annotations
  annotations:
    imageregistry: "https://hub.docker.com/"
    docker.com: "https://hemanchadra/post/k8s/"
spec:
  containers:
  - name: nginx
    image: nginx